name: <your project name>
services:
    v2fly-core:
        container_name: v2ray
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TARGETPLATFORM: linux/arm64/v8
                TAG: v5.22.0 #version
        volumes:
             - ./etcv2ray:/usr/local/etc/v2ray
#            - ./config.json:/etc/v2ray/config.json
        ports:
            - 8443:8443
#        image: v2fly/v2fly-core
        command: run -c /usr/local/etc/v2ray/config.json -format jsonv5
